spring:
  application:
    name: GatewayHMS

  cloud:
    gateway:
      default-filters:
        # ✅ Duplicate response headers hata dega
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"   # ✅ sirf frontend origin
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: userms
          uri: lb://UserMS
          predicates:
            - Path=/users/**
          filters:
            - name: JwtFilter
            
        - id: ProfileMS
          uri: lb://ProfileMS
          predicates:
            - Path=/profile/**
          filters:
            - name: JwtFilter

        - id: AppointmentMS
          uri: lb://Appointment
          predicates:
            - Path=/appointments/**
          filters:
            - name: JwtFilter
          
server:
  port: 9000





